-- Create portfolios table
create table portfolios (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  symbol text not null,
  shares numeric not null check (shares >= 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, symbol)
);

-- Create user_settings table
create table user_settings (
  user_id uuid references auth.users not null primary key,
  buying_power numeric default 10000 check (buying_power >= 0),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table portfolios enable row level security;
alter table user_settings enable row level security;

-- Policies for portfolios
create policy "Users can view their own portfolios"
  on portfolios for select
  using (auth.uid() = user_id);

create policy "Users can insert their own portfolios"
  on portfolios for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own portfolios"
  on portfolios for update
  using (auth.uid() = user_id);

create policy "Users can delete their own portfolios"
  on portfolios for delete
  using (auth.uid() = user_id);

-- Policies for user_settings
create policy "Users can view their own settings"
  on user_settings for select
  using (auth.uid() = user_id);

create policy "Users can insert their own settings"
  on user_settings for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own settings"
  on user_settings for update
  using (auth.uid() = user_id);
